

export const env: any = {
    DB_PASSWORD: process.env.DB_PASSWORD??"null",
    DB_USER_NAME: process.env.DB_USER_NAME??"null",
    DB_NAME: process.env.DB_NAME??"null",
    JWT_SECRET: process.env.JWT_SECRET??"null",

    WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID??"null",
    WHATSAPP_BUSINESS_ACCOUNT_ID: process.env.WHATSAPP_BUSINESS_ACCOUNT_ID??"null",
    WHATSAPP_SYSTEM_USER_TOKEN: process.env.WHATSAPP_SYSTEM_USER_TOKEN??"null",

    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID??"null",
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET??"null",
    RAZORPAY_WEBHOOK_SECRET:process.env.RAZORPAY_WEBHOOK_SECRET??"null",
    YOUR_RAZORPAY_VIRTUAL_ACCOUNT: process.env.YOUR_RAZORPAY_VIRTUAL_ACCOUNT??"null",

    PUBLIC_GOOGLE_MAPS_API_KEY:"null"
}


// export const env: any = {
//     DB_PASSWORD: "ydEjlYTJtUXPiGuS",
//     DB_USER_NAME: "sahal",
//     DB_NAME: "ARP_QA",
//     JWT_SECRET: "arp_rentitirsByWebcos01_userTokenKey",

//     WHATSAPP_PHONE_NUMBER_ID: "838907125976720",
//     WHATSAPP_BUSINESS_ACCOUNT_ID: "1277960014088191",
//     WHATSAPP_SYSTEM_USER_TOKEN: "EAAXXt3ZACnjMBP8BCjVf5jxVy3nafe6ZApCH4kHMkRxw8sW6ukAbvcOIJEQr9ALD8GjlIU6usZAMdE3NPtZCOKZBoZCfLjQICUSWZBT7fIs5WJIMCQldZCZAerhdYYam4r5EDrYHzrYjyFZANeHBaDs4Uaf4AmidI52zHJWNVSoYQEkrh3y984VMciMShnbpYX9QSu9AZDZD",

//     RAZORPAY_KEY_ID: "rzp_test_RQajTWhiooP6Nm",
//     RAZORPAY_KEY_SECRET: "ImkY0Rx0up8AmPCQjSskNbeS",
//     RAZORPAY_WEBHOOK_SECRET: "NULL",
//     YOUR_RAZORPAY_VIRTUAL_ACCOUNT: "NULL",

//     PUBLIC_GOOGLE_MAPS_API_KEY: "NULL",
// }