

export const env: any = {
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_USER_NAME: process.env.DB_USER_NAME,
    DB_NAME: process.env.DB_NAME,
    JWT_SECRET: process.env.JWT_SECRET,

    WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_BUSINESS_ACCOUNT_ID: process.env.WHATSAPP_BUSINESS_ACCOUNT_ID,
    WHATSAPP_SYSTEM_USER_TOKEN: process.env.WHATSAPP_SYSTEM_USER_TOKEN,

    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    RAZORPAY_WEBHOOK_SECRET:process.env.RAZORPAY_WEBHOOK_SECRET,
    YOUR_RAZORPAY_VIRTUAL_ACCOUNT: process.env.YOUR_RAZORPAY_VIRTUAL_ACCOUNT,
    
    PUBLIC_GOOGLE_MAPS_API_KEY:"null"
}

