export const env: any = {
    DB_PASSWORD: "ydEjlYTJtUXPiGuS",
    DB_USER_NAME: "sahal",
    DB_NAME: "ARP_QA",
    JWT_SECRET: "arp_rentitirsByWebcos01_userTokenKey",

    WHATSAPP_TOKEN: "",
    WHATSAPP_PHONE_NUMBER_ID: "838907125976720",
    WHATSAPP_BUSINESS_ACCOUNT_ID: "1277960014088191",
    WHATSAPP_SYSTEM_USER_TOKEN: "EAAXXt3ZACnjMBP8BCjVf5jxVy3nafe6ZApCH4kHMkRxw8sW6ukAbvcOIJEQr9ALD8GjlIU6usZAMdE3NPtZCOKZBoZCfLjQICUSWZBT7fIs5WJIMCQldZCZAerhdYYam4r5EDrYHzrYjyFZANeHBaDs4Uaf4AmidI52zHJWNVSoYQEkrh3y984VMciMShnbpYX9QSu9AZDZD",

    RAZORPAY_KEY_ID: "rzp_test_RQajTWhiooP6Nm",
    RAZORPAY_KEY_SECRET: "ImkY0Rx0up8AmPCQjSskNbeS",
    RAZORPAY_WEBHOOK_SECRET: "",
    YOUR_RAZORPAY_VIRTUAL_ACCOUNT: "",
    AISENSY_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmNiZWY4MDhkYzk2MDNhODNhZjIyMSIsIm5hbWUiOiJ3ZWJjb3MiLCJhcHBOYW1lIjoiQWlTZW5zeSIsImNsaWVudElkIjoiNjhmY2JlZjgwOGRjOTYwM2E4M2FmMjFjIiwiYWN0aXZlUGxhbiI6IkZSRUVfRk9SRVZFUiIsImlhdCI6MTc2MTM5NDQyNH0.Ia4Y2eFQDaQGGUkC43NhfIH_bb1U6qwAXXF6je6zPnA"
}

