export const whatsapp_config = {
    WHATSAPP_TOKEN:"EAAcxRCuLFAYBPsrHfoNJ6sW8rhwJbeLcvo1UZCWXxXrwkN0YuiBbOtTI6mxGbhvdO1azDnRMGDj9ys4Id3xINVRKAZCw0b2mp2NrZC17wNZCtpcMUgcLy4NanuQmIE1slGsTeiLxmusGaHFB3Rd5SltmG6gtzZCvnEbmW5oeHZBcViRcZCZAU6VOXzBvSZBrXs8EKchimyI5UKtJzfq9uU8Awz1CcuZCyRNAUxMduV1eCZB",
    WHATSAPP_PHONE_NUMBER_ID: "817398818124323"
}

export const razorpay_config = {
  RAZORPAY_KEY_ID:"rzp_test_RQajTWhiooP6Nm",
  RAZORPAY_KEY_SECRET:"ImkY0Rx0up8AmPCQjSskNbeS",
  RAZORPAY_WEBHOOK_SECRET:"",
  YOUR_RAZORPAY_VIRTUAL_ACCOUNT:""
}