 export const countryCodes = [
    { code: "+91", name: "India" },
    { code: "+1", name: "USA" },
    { code: "+44", name: "UK" },
    { code: "+81", name: "Japan" },
    { code: "+86", name: "China" },
  ];

export const subscription_plans = [
  {
    name: "Basic",
    price: "₹199",
    period: "per month",
    price_yearly: "₹2299",
    description: "Perfect for new landlords managing a few assets.",
    features: [
      "1 property",
      "Up to 10 rooms",
      "Up to 30 booking",
      "Email support",
      "1 month free trial ",
    ],
    total_properties: 1,
    total_rooms: 10,
    total_bookings: 30,
    buttonText: "Start Free",
    buttonLink: "/auth/signup",
    buttonStyle: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    borderColor: "border-transparent",
    highlight: false,
  },
  {
    name: "Pro",
    price: "₹499",
    period: "per month",
    price_yearly: "₹4899",
    description: "The best choice for professional property managers.",
    features: [
      "Up to 10 properties",
      "Up to 300 rooms",
      "Up to 500 booking",
      "Automated invoicing & payments",
      "Advanced analytics dashboard",
      "Priority support",
    ],
    total_properties: 10,
    total_rooms: 100,
    total_bookings: 300,
    buttonText: "Choose Pro",
    buttonLink: "/auth/signup?plan=pro",
    buttonStyle: "bg-green-700 text-white hover:bg-green-600",
    borderColor: "border-green-700",
    highlight: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "per month",
    description: "Solutions for large-scale portfolios and custom features.",
    features: [
      "Unlimited properties",
      "Dedicated account manager",
      "SLA & custom integrations",
    ],
    total_properties:"UNLIMITED",
    total_rooms:"UNLIMITED",
    total_bookings:"UNLIMITED",
    buttonText: "Contact Sales",
    buttonLink: "/contact/sales",
    buttonStyle: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    borderColor: "border-transparent",
    highlight: false,
  },
];

