import { SubscritptionBillingCycle } from "./contants";

 export const countryCodes = [
    { code: "+91", name: "India" },
    { code: "+1", name: "USA" },
    { code: "+44", name: "UK" },
    { code: "+81", name: "Japan" },
    { code: "+86", name: "China" },
  ];

export const subscription_plans = [
    {
    id:"arp_subcription_trial",
    name: "Free Trial",
    amount: 0,
    price: "₹0",
    no_price:true,
    description: "Perfect for new landlords managing a few assets.",
    property_limit:1,
    features: [
      "14 days free trial ",
      "1 property",
      "Up to 10 rooms",
      "Up to 30 booking",
      "Email support",
    ],
    total_properties: 1,
    total_rooms: 10,
    total_bookings: 30,
    buttonText: "Start Free trial",
    buttonLink: "/subscription",
    buttonStyle: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    borderColor: "border-transparent",
    highlight: false,
  },
  {
    id:"arp_subcription_base21",
    name: "Basic",
    amount: 199,
    price: "₹199",
    period: "per month",
    no_price:false,
    billingCycle:SubscritptionBillingCycle.MONTHLY,
    price_yearly: "₹2299",
    description: "Perfect for new landlords managing a few assets.",
    property_limit:1,
    features: [
      "14 days free trial ",
      "1 property",
      "Up to 10 rooms",
      "Up to 30 booking",
      "Email support",
    ],
    total_properties: 1,
    total_rooms: 10,
    total_bookings: 30,
    buttonText: "Choose Basic",
    buttonLink: "/subscription?plan=basic",
    buttonStyle: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    borderColor: "border-transparent",
    highlight: false,
  },
  {
    id:"arp_subcription_pro47",
    name: "Pro",
    amount: 499,
    price: "₹499",
    period: "per month",
    no_price:false,
    billingCycle:SubscritptionBillingCycle.MONTHLY,
    price_yearly: "₹4899",
    description: "The best choice for professional property managers.",
    property_limit:10,
    features: [
      "Up to 10 properties",
      "Up to 300 rooms",
      "Up to 500 booking",
      "Automated invoicing & payments",
      "Advanced analytics dashboard",
      "Priority support",
    ],
    total_properties: 10,
    total_rooms: 100,
    total_bookings: 300,
    buttonText: "Choose Pro",
    buttonLink: "/subscription?plan=pro",
    buttonStyle: "bg-green-700 text-white hover:bg-green-600",
    borderColor: "border-green-700",
    highlight: true,
  },
  {
    id:"arp_subcription_cus74",
    name: "Enterprise",
    price: "Custom",
    period: "per month",
    no_price:true,
    description: "Solutions for large-scale portfolios and custom features.",
    property_limit:"unlimited",
    features: [
      "Unlimited properties",
      "Dedicated account manager",
      "SLA & custom integrations",
      "Automated invoicing & payments",
      "Advanced analytics dashboard",
      "Priority support",
    ],
    total_properties:"UNLIMITED",
    total_rooms:"UNLIMITED",
    total_bookings:"UNLIMITED",
    buttonText: "Contact Sales",
    buttonLink: "/contact",
    buttonStyle: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    borderColor: "border-transparent",
    highlight: false,
  },
];

